# Shopify API access
shopify:
  api-url: https://wallet-top-up.myshopify.com
  api-key: bee9d4b0e98978fd3ec5e7625ef2838e
  api-password: 50387a70e75f66fc2330062edc38b7f2
  secret: 4aa1c538138e6dcb09f6d4d92ba4087c14415079c26fb6fb8a51bc6e6dca5ca3
  location-id: 18618777700

# JWT configuration by Auth0
auth0:
  issuer: https://wallettopup.auth0.com/
  apiAudience: https://wallettopup.auth0.com/api/v2/

# testnet/regtest/mainnet
bitcoinj:
  network:
    type: testnet

# Spring Reference https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

server.port: 8080

logging:
  level:
    root: INFO
    org.bitcoinj: INFO
  pattern:
    console: "%d %-5level| %logger{10} : %msg%n"