# Shopify API access
shopify:
  api-url: https://wallet-top-up.myshopify.com
  #  shop-name: wallet-top-up
  api-key: bee9d4b0e98978fd3ec5e7625ef2838e
  api-password: 50387a70e75f66fc2330062edc38b7f2
  secret: 4aa1c538138e6dcb09f6d4d92ba4087c14415079c26fb6fb8a51bc6e6dca5ca3
  # see this for location ids: https://wallet-top-up.myshopify.com/admin/products/inventory?location_id=18633130084&query=
  location-id: 18633130084

# JWT configuration by Auth0
auth0:
  issuer: https://wallettopup.auth0.com/
  apiAudience: https://wallettopup.auth0.com/api/v2/

# testnet/regtest/mainnet
bitcoinj:
  network:
    type: testnet

es.coffeebyt.notification:
  # topic with results of user actions
  orders-topic-arn: "arn:aws:sns:eu-west-2:367570967874:orders"
  redemptions-topic-arn: "arn:aws:sns:eu-west-2:367570967874:redemptions"
  # IAM sns-access-user
  access-key-id: "AKIAITMQC6R6A773KPNQ"
  secret-key-id: "na4eftnibgdw4GXj9+cnDyGTYYY60MG8adIpYttM"

# Spring Reference https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  # Gmail
  mail:
    host: smtp.gmail.com
    port: 587
    username: hubert.czerpak@gmail.com
    password: iqsootamnlofucas
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://aa9bbsh8k7xriq.cmt4otxvbkhv.eu-west-2.rds.amazonaws.com:5432/postgres
    username: mieszko
    password: koleszko
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc.lob.non_contextual_creation: true
      ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

management:
  endpoints:
    web:
      base-path: /api
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

server:
  port: 5000

# Amazon SES Service
#spring.mail.host=email-smtp.us-west-2.amazonaws.com
#spring.mail.username=username
#spring.mail.password=password
#spring.mail.properties.mail.transport.protocol=smtp
#spring.mail.properties.mail.smtp.port=25
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
# Please, be aware that Amazon requires you to verify your credentials before using them. Follow the link
# http://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-email-addresses.html to verify your username and password.

logging:
  level:
    root: INFO
    org.bitcoinj.net.NioClientManager: ERROR
    org.bitcoinj.net.ConnectionHandler: ERROR

feign:
  okhttp:
    enabled: true
  client:
    config:
      shopify:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        #        errorDecoder: com.example.SimpleErrorDecoder
        #        retryer: com.example.SimpleRetryer
        #        requestInterceptors:
        #          - com.example.FooRequestInterceptor
        #          - com.example.BarRequestInterceptor
        #        decode404: false
        encoder: feign.jackson.JacksonEncoder
        decoder: feign.jackson.JacksonDecoder