# JWT configuration by Auth0
#auth0:
#  issuer:
#  apiAudience:

# Spring Reference https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    org.bitcoinj: INFO
    cash.bitcoinj: INFO
    es:
      coffeebyt:
        wtu:
          notifications:
            impl: DEBUG

es:
  coffeebyt:
    bitcoinj:
      auto-start: false
      # testnet/regtest/mainnet
      network:
        type: testnet
    jlibra:
      network:
        address: "localhost"
        port: 999
